version: "3.6"
 
services:
 
  zabbix-mysql:
    image: mysql:8.0
    container_name: zabbix-mysql
    hostname: zabbix-mysql
    restart: always
    command:  [mysqld, --character-set-server=utf8, --collation-server=utf8_bin]
    environment:
      TZ: "Asia/Tomsk"
      MYSQL_ROOT_PASSWORD: TeleDracele1234
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: TeleDracele1234
    networks:
      - zabbix-net
    volumes:
      - ./mariadb/data:/var/lib/mysql


  zabbix-java-gateway:
    image: zabbix/zabbix-java-gateway:latest
    networks:
       - zabbix-net
 
  zabbix-server:
    image: zabbix/zabbix-server-mysql:6.0-alpine-latest
    container_name: zabbix-server
    hostname: zabbix-server
    restart: always
    environment:
      TZ: "Asia/Tomsk"
      DB_SERVER_HOST: zabbix-mysql
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: TeleDracele1234
      ZBX_JAVAGATEWAY: zabbix-java-gateway
    ports:
      - 10051:10051
    networks:
      zabbix-net:
        ipv4_address: 172.28.0.254
    depends_on:
      - zabbix-mysql
      - zabbix-java-gateway
 
  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:6.0-alpine-latest
    container_name: zabbix-web
    hostname: zabbix-web
    restart: always
    environment:
      TZ: "Asia/Tomsk"
      DB_SERVER_HOST: zabbix-mysql
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: TeleDracele1234
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: "Asia/Tomsk"
    ports:
      - 8088:8080
      - 8443:8443
    networks:
      - zabbix-net
    depends_on:
      - zabbix-mysql
      - zabbix-server

networks:
  zabbix-net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
